spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/anitebeti
    username: postgres
    password: everlearnPSQL
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.hibernate: DEBUG